export const ERRORS = {
    NOT_AN_OBJECT: 'Request data is not an object',
    NAME_NOT_A_STRING: 'Name is not a string',
    NAME_NOT_ENTERED: 'User property "name" not entered or spelled incorrectly',
    LOGIN_NOT_ENTERED: 'User property "login" not entered or spelled incorrectly',
    PASSWORD_NOT_ENTERED: 'User property "password" not entered or spelled incorrectly',
    AGE_NOT_NUMBER: 'Age is not a number',
    PASSWORD_NOT_STRING: 'Password is not a string',
    USER_NOT_FOUND: 'User with requested ID not found. Please check ID input',
    WRONG_ID_FORMAT: 'ID format is not the format that the UUID suggests (XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)',
    ENDPOINT_NOT_FOUND: 'End point not found',
    JSON_PARSE_ERR: 'JSON parse error',
    LOGIN_IS_NOT_A_STRING: 'Login is not a string',
    TITLE_NOT_ENTERED: 'Board property "title" not entered or spelled incorrectly',
    TITLE_NOT_A_STRING: 'Title is not a string',
    COLUMNS_IS_NOT_AN_ARRAY: 'Columns arrnt an array',
    BOARD_NOT_FOUND: 'Board with requested ID not found. Please check ID input',
    TASK_NOT_FOUND: 'Task with requested ID not found. Please check ID input',
    TASK_IN_BOARD_NOT_FOUND: 'Task in board with requested ID not found. Please check ID input',
    ORDER_NOT_ENTERED: 'Task property "order" not entered or spelled incorrectly',
    ORDER_IS_NOT_A_STRING: 'Order is not a string',
    DESCRIPTION_NOT_ENTERED: 'Task property "description" not entered or spelled incorrectly',
    DESCRIPTION_IS_NOT_A_STRING: 'Order is not a string',
    USERID_IS_NOT_A_STRING_OR_NULL: 'UserId is not a string or Null',
    USERID_NOT_ENTERED: 'Task property "userId" not entered or spelled incorrectly',
    COLUMN_NOT_ENTERED: 'Task property "columnId" not entered or spelled incorrectly',
    COLUMN_IS_NOT_A_STRING: 'ColumnId is not a string',
}